### ISSUE TITLE
much less math, some more words

### ISSUE THREAD

**Issue by davidwhogg** [dfm/linear-models#2]
I say (and I say this in an `\alltodo{}`): Drop most of the math, call out to various identities and deep ideas in math (like convos of Gaussians are Gaussians), and use the liberated word count to add a final implications section which says various things of importance about what this MEANS for data analysis and what capabilities it makes. Oh and when the solution will be fast.

**Comment by rodluger** [comment]
I'm all for that punchline ending, but apparently equations don't count
towards the word limit, at least according to their word count tool!

**Comment by dfm** [comment]
I'm inclined to keep the math for now and just add more words. We can edit later if we need to. I think that the equations are important for the pedagogical impact.

**Comment by davidwhogg** [comment]
First author's call. I just want the main result, which (IMO) is the Gaussian with (C + ALA), to appear clearly as *the result*. As in: The message of the paper should be: **Simple Result!** not **Complex math!**. Right now it is easy to miss the main result in a skim.

**Comment by dfm** [comment]
Understood. That makes sense. Maybe we can have an appendix in our note....

**Comment by davidwhogg** [comment]
LOVE IT. Four sections and an appendix, plus acks and refs, and <1000 words.

**Comment by dfm** [comment]
Done.

**Comment by dfm** [comment]
~1000 words (maybe a few over.......)
