### ISSUE TITLE
math typography

### ISSUE THREAD

**Issue by davidwhogg** [dfm/linear-models#3]
- [x]  I would use `\,` thin spaces as multiplies as in `\int p(foo)\,p(blah)\,\dd\vw`
- [x] I would use `||V||` not `|V|` for determinant
- [x] I would put the `2\pi` into the determinants, that way you don't have to explicitly call out dimensions anywhere: use `||2\pi\,V||^{1/2}` rather than `(2\pi)^{D/2}\,||V||^{1/2}`

**Comment by dfm** [comment]
I agree about the spaces but \dd already includes it.

I disagree about the suggested determinant notation.

2pi inside is cool.

**Comment by rodluger** [comment]
Working on all this right now.
